### ISSUE TITLE
Fail to properly deserialize sequences

### ISSUE THREAD

**Issue by bnjbvr** [nox/serde_urlencoded#109]
The following test fails:

```rust
#[test]
fn deserialize_sequence() {
    #[derive(Debug, PartialEq, Deserialize)]
    struct Parsed {
        key: Vec<u64>,
    }
    let parsed = Parsed { key: vec![1, 2] };
    assert_eq!(serde_urlencoded::from_str("key=val1&key=val2"), Ok(parsed));
}

#[test]
fn deserialize_sequence2() {
    let parsed = vec![("key".to_owned(), vec![1, 2])];
    assert_eq!(serde_urlencoded::from_str("key=val1&key=val2"), Ok(parsed));
}
```

This kind of urlencoded data can be produced by the following form:

```html
 <form action="/api/test" method="post">
                <p>
                    <label for="select">Impacted services:</label><br />
                    <select id="select" name="key" multiple required>
                        <option value="val1">First</option>
                        <option value="val2">Second</option>
                    </select>
                </p>
                <p>
                    <input type="submit" value="submit" />
                </p>
</form>
```

**Comment by nox** [comment]
This is out of scope for serde_urlencoded, use serde_qs if you want to use sequences.

**Comment by hseeberger** [comment]
I do not think, that repeated parameters should be out of scope, because they are clearly possible according to the [spec](https://url.spec.whatwg.org/#concept-urlencoded).

serde_qs treats sequences differently: one has to specify the index for each element, e.g. `"user_ids[1]=2&user_ids[2]=3&user_ids[3]=4"`. 

But there are use cases for APIs and HTML forms to allow "simple" repeated parameters, e.g. `"user_id=2&user_id=3&user_id=4"`. This should be deserialized into something like `user_id = vec![2, 3, 4]`.

**Comment by nox** [comment]
This is not up for debate, this crate won't ever support sequences.
