### ISSUE TITLE
Serialize Vec<T>

### ISSUE THREAD

**Issue by nbigaouette** [nox/serde_urlencoded#6]
I need to serialize using `serde_urlencoded::to_string()` a `Vec<i64>` into `name[]=val1&name[]=val2&...`.

It does not seems possible `serde_urlencoded`... or am I missing something?

**Comment by nox** [comment]
It's not currently possible, I've wished to implement it for a while now, will probably look at it next week.

**Comment by nbigaouette** [comment]
To make things more "interesting", I would also need the `Vec` to be serialized to `name=val1,val2,val3,...` Would that be possible too?

**Comment by nox** [comment]
I won't support the comma separated thing, but the repeated key name yes.

**Comment by samscott89** [comment]
Hey @nbigaouette, I've created [serde_qs](https://github.com/samscott89/serde_qs) to try and fill this gap, since I think the extra functionality needed would be unnecessarily cumbersome to this library. 

Let me know if it's suitable for your use case. I showed [in the examples](https://github.com/samscott89/serde_qs/blob/master/examples/csv_vectors.rs) how you could also support the comma-separated vector lists (though actually the same strategy would presumably work fine here as well).

**Comment by antoine-de** [comment]
Just to be sure to understand, you don't plan to support the repeated key name ? You suggest [serde_qs](https://github.com/samscott89/serde_qs)  for this too ?

**Comment by nox** [comment]
```rust
struct Params {
    foo: Vec<i32>,
    bar: String,
}

serde_urlencoded::from_bytes(b"foo=23&bar=baguette&foo=42")
```

Handling sequences mean traversing the entire string to get all the pairs with the same key, and only then you can deserialise that to a `Vec<i32>`, I won't accept any such patch in this crate, but AFAIK this kind of thing isn't out of scope for `serde_qs`.

**Comment by samscott89** [comment]
> Handling sequences mean traversing the entire string to get all the pairs with the same key, and only then you can deserialise that to a Vec<i32>, I won't accept any such patch in this crate, but AFAIK this kind of thing isn't out of scope for serde_qs.

Yeah, this is true to the extent of my understanding. The performance of serde_qs is significantly worse than serde_urlencoded due to this, so keeping the separation seems like a good idea to me. 

And yes, [serde_qs](https://docs.rs/serde_qs/0.4.3/serde_qs/) can handle most structs. In the case of vecs, you can either use indexed arrays `foo[0]=...&foo[1]=...` or unindexed, `foo[]=...&foo[]=...`.

**Comment by lnicola** [comment]
@samscott89 is `serde_qs` supposed to handle percent-encoded brackets? `s[]=1+2&s[]=2` seems to work, but `s%5B%5D=1+2&s%5B%5D=2` doesn't.

@nox `serde_urlencoded` advertises support for `application/x-www-form-urlencoded`, but this issue makes that feel misleading.

**Comment by nox** [comment]
How is that misleading? `application/x-www-form-urlencoded` specifically doesn't have any concept of nesting or even serialising a sequence of values. This crate (and `url`) does handle percent-encoded brackets, as the WHATWG URL Standard says to do it.

**Comment by lnicola** [comment]
Misleading for someone who wants to use it for something that looks like an array sent by a web browser :-).

**Comment by nox** [comment]
There is no standard for that and not every backend tooling handle such things with brackets. For example some Perl libraries just deserialise multiple entries with the same key as an array, which is why I decided to not support this feature in this crate directly.

**Comment by antoine-de** [comment]
@lnicola serde_qs handles this, but in [non strict mode](https://docs.rs/serde_qs/0.5.0/serde_qs/#strict-vs-non-strict-modes). I have an example [here](https://github.com/CanalTP/mimirsbrunn/blob/master/libs/bragi/src/extractors.rs#L70).
