### ISSUE TITLE
Deserializing &str should not be supported

### ISSUE THREAD

**Issue by djc** [nox/serde_urlencoded#65]
It seems to me like the support for deserializing &str should probably be removed (always failing with a panic). Otherwise, whether it works or not is dependent on whether the value to be deserialized contains any special characters, which seems like a footgun. I'm not sure if this is a problem with the changes in #54, but it might be related. If someone wants to avoid this issue, they can put a `Cow<'a, str>` in their types instead.

**Comment by nox** [comment]
Nah, I like this, even if some may consideer it's a hack.

**Comment by paholg** [comment]
I'd like to add a vote for this. I saw that you already said you like it, but can you explain why?

I see no benefit to allowing this. If you know no decoding needs to be performed, just don't use this crate in the first place.

This is especially problematic because `serde_urlencoded` will often be called by a dependency; you can run into bugs here without even knowing this crate exists.
