### ISSUE TITLE
Please publish a new version

### ISSUE THREAD

**Issue by jplatte** [nox/serde_urlencoded#83]
In particular because of #74, #79.

**Comment by nox** [comment]
Doing this now.

**Comment by lovasoa** [comment]
Hello ! 
  Just a friendly reminder about version numbers: 

 - you could have switched from 0.6.1 to 0.6.1, since the changes seem to be backwards compatible.
 - It would be nice if there were a CHANGELOG in the repo.
 - This crate is being used by many other major stable crates, such as `actix-web`, and is thus being used in production by a lot of people. Would you consider switching to 1.x and guarantee backward compatibility ? 

https://semver.org/

**Comment by nickelc** [comment]
>     * you could have switched from 0.6.1 to 0.6.1, since the changes seem to be backwards compatible.
The changes are not backwards compatible because `form_urlencoded::Serializer` (`url::form_urlencoded::Serializer` with v0.6) is part of the [public api][docs].

[docs]: https://docs.rs/serde_urlencoded/0.7.0/serde_urlencoded/struct.Serializer.html#method.new

**Comment by nox** [comment]
> It would be nice if there were a CHANGELOG in the repo.

Patches welcome.

> This crate is being used by many other major stable crates, such as actix-web, and is thus being used in production by a lot of people. Would you consider switching to 1.x and guarantee backward compatibility ?

No.
